### ISSUE TITLE
mutualaid.wiki domain seems to have gone down.

### ISSUE THREAD

**Issue by wu-lee** [DigitalCommons/covid-mutual-aid-project#3]
This is arguably an open-data issue, but relates to this map, because the map data isn't being updated.

The download is failing, because "mutualaid.wiki:443 (getaddrinfo: Name or service not known) " - in other words, the domain is no longer resolving.  Output from the data feed processor  AKA sausage machine:

```
May 31 09:42:59 dev-1 sync-and-run[484090]: PROCESSING covid-mutual-aid...
May 31 09:42:59 dev-1 sync-and-run[484935]: [For covid-mutual-aid: bundle install --quiet]
May 31 09:43:00 dev-1 sync-and-run[484935]: [For covid-mutual-aid: bundle exec seod download]
May 31 09:43:02 dev-1 sync-and-run[485016]:   invoking command: download
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! /usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to mutualaid.wiki:443 (getaddrinfo: Name or service not known) (SocketError)
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:606:in `start'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:650:in `head'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:670:in `etag'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:217:in `command_http_download'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/covid-mutual-aid/downloader:13:in `<main>'
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! /usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': getaddrinfo: Name or service not known (SocketError)
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /usr/lib/ruby/2.7.0/net/http.rb:606:in `start'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:650:in `head'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:670:in `etag'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:217:in `command_http_download'
May 31 09:43:02 dev-1 sync-and-run[485016]:     !         from /home/seopendata/working/covid-mutual-aid/downloader:13:in `<main>'
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! 'downloader' command in current directory failed
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/lib/se_open_data/cli.rb:282:in `command_download'
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! /home/seopendata/working/caches/gems/se-open-data-8c8f294b831d/bin/seod:128:in `<top (required)>'
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! /home/seopendata/working/covid-mutual-aid/.gems/ruby/2.7.0/bin/seod:23:in `load'
May 31 09:43:02 dev-1 sync-and-run[485016]:     ! /home/seopendata/working/covid-mutual-aid/.gems/ruby/2.7.0/bin/seod:23:in `<main>'
May 31 09:43:02 dev-1 sync-and-run[484090]: FAILED covid-mutual-aid (return code 255)
```

The `whois` lookup for mutualaid.wiki gets:
```
Domain Name: mutualaid.wiki
Registry Domain ID: D182766289CNIC-GDREG
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: http://www.namecheap.com
Updated Date: 2023-04-30T00:40:28Z
Creation Date: 2020-04-14T10:01:30Z
Registry Expiry Date: 2023-04-14T23:59:59Z
Registrar: NameCheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: pendingDelete https://icann.org/epp#pendingDelete
Domain Status: redemptionPeriod https://icann.org/epp#redemptionPeriod
[... snip ...]
```

Which supports my hypothesis that they've lapsed in their payments, deliberately or accidentally. Looks like the domain stopped working on 30th April, and is in a "redemption period", "pending delete" with "client transfer prohibited".

**Comment by ColmDC** [comment]
Shall we stop attempting to upload new data, but keep publishing the last version we received?

**Comment by wu-lee** [comment]
Okaydoke.  That just means removing this feed from the sausage machine's list.  The data will stay as it is.

**Comment by wu-lee** [comment]
Ok, should be done now, on dev-1 and prod-1. Will check the errors have disappeared on an hour or so.

**Comment by ColmDC** [comment]
> Moving this to QA to ask - wondering if should we contact the people behind this site? However, I can't find the email address.

I can't find the details either. Let's just modify the about box to say

The data used to generate this map and was taken from the project formerly hosted at https://mutualaid.wiki/map.

**Comment by ColmDC** [comment]
Hi Nick,

Thanks for bringing this to my attention! The domain expired. I have renewed it and it should be running as usual again.

Take care,
Julian

**Comment by ColmDC** [comment]
Happy to close this @wu-lee ?
